[package]
name = "CVE-2021-25907_bug"
version = "0.1.0"
edition = "2018"

[dependencies]
containers = {git = "https://github.com/strake/containers.rs", rev = "d27a2677db4225b2b3744229b0234c500dcd3a83"}