[package]
name = "CVE-2019-16880_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
linea = {git = "https://github.com/Phosphorus15/linea.rs", rev = "9d2fba1f76d076478b50446e4738c219516e63d8"}