[package]
name = "CVE-2020-36437_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
conqueue = {git = "https://github.com/longshorej/conqueue", rev = "1e462c32e7933821ddb26dc49fd4ffa5aeca97b8"}