[package]
name = "CVE-2020-36208_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
conquer-once = {git = "https://github.com/oliver-giersch/conquer-once", rev = "06db899114401235392321af8225b55e2290e1f6"}
crossbeam-utils = "0.8"   