[package]
name = "CVE-2020-36439_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
ticketed_lock = {git = "https://github.com/kvark/ticketed_lock", rev = "6d85af9eb5d8bb7cf142de8e832ce3af7e47e306"}