[package]
name = "CVE-2021-45684_repair"
version = "0.1.0"
edition = "2018"

[dependencies]
flumedb = {git = "https://github.com/sunrise-choir/flumedb-rs", rev = "1b643df85ca4a56f7d96105a9eb35e1b917ee488"}