[package]
name = "CVE-2020-36210_bug"
version = "0.1.0"
edition = "2018"

[dependencies]
autorand = {git = "https://github.com/mersinvald/autorand-rs", rev = "c838309507f9364ecf61553a6ae113dd720fdab9"}