[package]
name = "CVE-2020-36445_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
convec = {git = "https://github.com/JOE1994/convec", rev = "88b86e290c7913a42c69bb6fcfc9e7eb585f4dae"}
crossbeam-utils = "=0.7.2"
