[package]
name = "CVE-2020-35902_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-codec = {git = "https://github.com/actix/actix-net", rev = "c41b5d8dd4235ccca84d0b687996615c0c64d956"}