[package]
name = "CVE-2020-35898_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-utils = {git = "https://github.com/JohnTitor/actix-net", rev = "5d6d309e66b79d837ede20a26d654274bfb68d8f"}