[package]
name = "CVE-2020-35888_repair"
version = "0.1.0"
edition = "2018"

[dependencies]
arr = {git = "https://github.com/sjep/array", rev = "34380d886168061149af0ee47fe07a74b7ebf4e2"}
crossbeam-utils = "=0.6.6"