[package]
name = "CVE-2021-45686_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
csv-sniffer = {git = "https://github.com/jblondin/csv-sniffer", rev = "d964e42e207975fcb42777297c988c2cf2a014a7"}