[package]
name = "CVE-2018-20995_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
slice-deque = {git = "https://github.com/gnzlbg/slice_deque", rev = "045fb28701d3b674b5da413266ca84b3e5a70190"}