[package]
name = "CVE-2018-20995_repair"
version = "0.1.0"
edition = "2018"

[dependencies]
slice-deque = {git = "https://github.com/gnzlbg/slice_deque", rev = "70c87a49451c4dfcb170461ad9c55fe2f104b7b4"}