[package]
name = "CVE-2020-36465_bug"
version = "0.1.0"
edition = "2018"

[dependencies]
generic-array = {git = "https://github.com/fizyk20/generic-array", rev = "171bc5ce17c7aacca3c701a23b6095bd98c48cfe"}