[package]
name = "CVE-2020-35901_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-http = {git = "https://github.com/JohnTitor/actix-web", rev = "dede6fef9a50650efdd1ee36b2466911cc1b1950"}
bytes        = "0.5"
futures      = "0.3"