[package]
name = "CVE-2021-25907_repair"
version = "0.1.0"
edition = "2018"

[dependencies]
containers = {git = "https://github.com/strake/containers.rs", rev = "7389a24d84ee7ff1d60dc87270882897679c4afa"}