[package]
name = "CVE-2020-25795_bug"
version = "0.1.0"
edition = "2018"

[dependencies]
sized-chunks = {git = "https://github.com/bodil/sized-chunks", rev = "40aa74b824688a4d4b1e1c65a50c679abb58b41e"}