[package]
name = "CVE-2021-28033_bug"
version = "0.1.0"
edition = "2018"

[dependencies]
byte_struct = {git = "https://github.com/wwylele/byte-struct-rs", rev = "9c41996e55bc91557edd6fa6f6a1c07a48c55731"}