[package]
name = "CVE-2020-36438_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_future = {git = "https://github.com/KizzyCode/tiny_future-rust", rev = "50bd80f874c851413a721bbe144eeba4dfb68b4e"}