[package]
name = "CVE-2021-29935_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket_http = {git = "https://github.com/SergioBenitez/Rocket", rev = "c24f15c18f02319be83af4f3c1951dc220b52c5e"}