[package]
name = "CVE-2020-36217_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
may = {git = "https://github.com/Xudong-Huang/may", rev = "d1cd3314b9ae36371b4a9ab4ea1d5da9030e0ef6"}
may_queue        = "=0.1.7"        #  last version *without* Send bound
crossbeam-utils  = "0.8"