[package]
name = "CVE-2019-16881_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
portaudio-rs = {git = "https://github.com/mvdnes/portaudio-rs", rev = "f282e8c9c37b86859f5a3c3f032cedc6b6a650da"}