[package]
name = "CVE-2020-35888_bug"
version = "0.1.0"
edition = "2018"

[dependencies]
arr = {git = "https://github.com/sjep/array", rev = "efa214159eaad2abda7b072f278d678f8788c307"}
crossbeam-utils = "=0.6.6"