[package]
name = "CVE-2021-28033_repair"
version = "0.1.0"
edition = "2018"

[dependencies]
byte_struct = {git = "https://github.com/wwylele/byte-struct-rs", rev = "a535678377de12bc6bc22620c5f59bcc1369f76f"}