[package]
name = "CVE-2021-29935_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket_http = {git = "https://github.com/SergioBenitez/Rocket", rev = "e325e2fce4d9f9f392761e9fb58b418a48cef8bb"}