[package]
name = "CVE-2020-36436_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
unicycle = {git = "https://github.com/udoprog/unicycle", rev = "c6a1e1601e8ddfb33d2846abca3c3ddc50e0493c"}
crossbeam-utils = "=0.7.2"