[package]
name = "CVE-2021-28032_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
nano_arena = {git = "https://github.com/bennetthardwick/nano-arena", rev = "f5306c73a0f8f260eb49f9f0a8509ef85f038244"}