[package]
name = "CVE-2019-16139_bug"
version = "0.1.0"
edition = "2018"

[dependencies]
compact_arena = {git = "https://github.com/llogiq/compact_arena", rev = "947fa6ebd24c9b03f7673400ef7e76fe6bb816b8"}