[package]
name = "CVE-2020-36446_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
signal-simple = {git = "https://github.com/JOE1994/signal-rust", rev = "5ded23d4b13bbcdb1bae4267379afffa326a1ef5"}