[package]
name = "CVE-2021-45684_bug"
version = "0.1.0"
edition = "2018"

[dependencies]
flumedb = {git = "https://github.com/sunrise-choir/flumedb-rs", rev = "65084ddde9a0bf407de314183c74b75d45da98e3"}