[package]
name = "CVE-2021-29937_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
telemetry = {git = "https://github.com/Yoric/telemetry.rs", rev = "2820cf12f2e08645fd6d1f15b4a90a54d6082a81"}