[package]
name = "CVE-2021-45703_bug"
version = "0.1.0"
edition = "2018"

[dependencies]
tectonic = {git = "https://github.com/tectonic-typesetting/tectonic", rev = "c86ad4140a7b59c4f5a1db2f0adbb966285e75cd"}