[package]
name = "CVE-2020-35898_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-utils = {git = "https://github.com/JohnTitor/actix-net", rev = "0dca1a705ad1ff4885b3491ecb809a808e1de66c"}