[package]
name = "CVE-2020-36439_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
ticketed_lock = {git = "https://github.com/kvark/ticketed_lock", rev = "a986a9335d591fa5c826157d1674d47aa525357f"}
futures = "=0.1.30"