[package]
name = "CVE-2020-35892_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
simple-slab = {git = "https://github.com/nathansizemore/simple-slab", rev = "5e0524c1db836e2192e1cd818848d96937c0b587"}