[package]
name = "CVE-2020-36216_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
eventio = {git = "https://github.com/petabi/eventio", rev = "55dd22f447492e272b75230c3d8108faa10c6fca"}
crossbeam-channel = "0.5"
pcap-parser      = { version = "0.14", features = ["serialize"] }