[package]
name = "CVE-2019-16881_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
portaudio-rs = {git = "https://github.com/mvdnes/portaudio-rs", rev = "3dfc728b0edc0c51f5177e3b1189b3230e488b3f"}