[package]
name = "CVE-2021-28032_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
nano_arena = {git = "https://github.com/bennetthardwick/nano-arena", rev = "6b83f9d0708337a9f8b709c1624a8587021ceba2"}