[package]
name = "CVE-2020-36216_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
eventio = {git = "https://github.com/petabi/eventio", rev = "53a04203613c8137865664ab98c304da37aa2379"}
crossbeam-channel = "0.5"
pcap-parser      = { version = "0.14", features = ["serialize"] }