[package]
name = "CVE-2019-16144_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
generator = {git = "https://github.com/Xudong-Huang/generator-rs", rev = "25963e871a1b951322f90e4c213472cccb3408f6"}