[package]
name = "CVE-2021-45703_repair"
version = "0.1.0"
edition = "2018"

[dependencies]
tectonic = {git = "https://github.com/tectonic-typesetting/tectonic", rev = "cdff034e6d93cdfdafd13d8c6956e22fa5a57b79"}