[package]
name = "CVE-2018-20998_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayfire = {git = "https://github.com/arrayfire/arrayfire-rust", rev = "cdd0c10b8ebc7b3378ce23e45769554aa42033b0"}