[package]
name = "CVE-2020-36444_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
async-coap = {git = "https://github.com/google/rust-async-coap", rev = "b76d91776508fe3091b08f5129d8a6caef49fe7c"}