[package]
name = "CVE-2021-28035_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
stack_dst = {git = "https://github.com/thepowersgang/stack_dst-rs", rev = "807e9d45019c02369e11d40bd181cbf7bb7981fc"}