[package]
name = "CVE-2019-15551_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
smallvec = {git = "https://github.com/servo/rust-smallvec", rev = "f96322b9243405cc82701cc73f1b19313b413ab4"}