[package]
name = "CVE-2020-36438_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_future = {git = "https://github.com/KizzyCode/tiny_future-rust", rev = "c7919199a0f6d1ce0e3c33499d1b37f862c990e4"}