[package]
name = "CVE-2020-35901_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-http = {git = "https://github.com/JohnTitor/actix-web", rev = "3033f187d2214fdb40c815d982fbf6f8a31bcd3f"}