[package]
name = "CVE-2020-36445_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
convec = {git = "https://github.com/JOE1994/convec", rev = "1591dcdda05fdbc5483333411c0c7ac7e16f61c7"}
crossbeam-utils = "=0.7.2"
