[package]
name = "CVE-2018-20991_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
smallvec = {git = "https://github.com/servo/rust-smallvec", rev = "1f4025218c4321ea42ad01d80dd6110def2d86d9"}