[package]
name = "CVE-2020-35902_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-codec = {git = "https://github.com/actix/actix-net", rev = "693d5132a944b260b68071b938b6b2e532a7982c"}
bytes       = "0.5"
futures     = "0.3"
pin-project = "0.4"