[package]
name = "CVE-2020-25795_repair"
version = "0.1.0"
edition = "2018"

[dependencies]
sized-chunks = {git = "https://github.com/bodil/sized-chunks", rev = "9668113612ebac0cde59ee0bf4877f9942bb410e"}
typenum      = "1"