[package]
name = "CVE-2020-36435_bug"
version = "0.1.0"
edition = "2018"

[dependencies]
ruspiro-singleton = {git = "https://github.com/RusPiRo/ruspiro-singleton", rev = "0565f8ef459bd336eda8a6a63d1d50cdb581c2b3"}