[package]
name = "CVE-2020-36210_repair"
version = "0.1.0"
edition = "2018"

[dependencies]
autorand = {git = "https://github.com/mersinvald/autorand-rs", rev = "39f9eae55395dbd8f5f75bb4d70dd9b8b29df1c3"}