[package]
name = "CVE-2020-36210_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
autorand = {git = "https://github.com/mersinvald/autorand-rs", rev = "565d508993936821950009ec4c7c1e33301db81e"}