[package]
name = "CVE-2021-45681_bug"
version = "0.1.0"
edition = "2018"

[dependencies]
derive-com-impl = {git = "https://github.com/Connicpu/com-impl", rev = "bc6bb5384cac1278e9e89e65400ff9e218b705d1"}