[package]
name = "CVE-2020-15254_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = {git = "https://github.com/crossbeam-rs/crossbeam", rev = "81ab18efc7376f3277a6359fdc20d00b4bcf911c"}