[package]
name = "CVE-2021-45693_bug"
version = "0.1.0"
edition = "2018"

[dependencies]
messagepack-rs = {git = "https://github.com/otake84/messagepack-rs", rev = "ceaf01318383b00ccc93e95f065b8fd0afcc8d68"}