[package]
name = "CVE-2017-1000430_repair"
version = "0.1.0"
edition = "2015"

[dependencies]
base64 = {git = "https://github.com/alicemaz/rust-base64", rev = "24ead980daf11ba563e4fb2516187a56a71ad319"}