[package]
name = "CVE-2018-20998_repair"
version = "0.1.0"
edition = "2018"

[dependencies]
arrayfire = {git = "https://github.com/arrayfire/arrayfire-rust", rev = "a5256f3e5e23b83eaad69699e0b04653aba04fb8"}