[package]
name = "CVE-2020-36465_repair"
version = "0.1.0"
edition = "2018"

[dependencies]
generic-array = {git = "https://github.com/fizyk20/generic-array", rev = "100b0f6b15fdd2a9ba19c5ab7ea63a19022d1cd2"}