[package]
name = "CVE-2020-36217_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
may = {git = "https://github.com/Xudong-Huang/may", rev = "37015c07df25f9fc964788bbbde3d8fb135ef36c"}
crossbeam-utils = "0.8"
may_queue="0.1.21"