[package]
name = "CVE-2020-36208_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
conquer-once = {git = "https://github.com/oliver-giersch/conquer-once", rev = "268301a"}
crossbeam-utils = "0.8" 