[package]
name = "CVE-2021-26954_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
qwutils = {git = "https://github.com/qwertz19281/rust_utils", rev = "f4eae5b2ffd5501aef1beb3d6a3540be5a908172"}