[package]
name = "CVE-2019-16139_repair"
version = "0.1.0"
edition = "2018"

[dependencies]
compact_arena = {git = "https://github.com/llogiq/compact_arena", rev = "eb413b3d47baea8e8a0b9ce2ccd8299b354d3b74"}