[package]
name = "CVE-2020-36435_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
ruspiro-singleton = {git = "https://github.com/RusPiRo/ruspiro-singleton", rev = "b0d2bd20eb40b9cbc2958b981ba2dcd9e6f9396e"}