[package]
name = "CVE-2021-29939_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
stackvector = {git = "https://github.com/Alexhuszagh/rust-stackvector", rev = "d0382d5ef903fc96bdcc08c02e36e6dd2eda11a5"}