[package]
name = "CVE-2021-30454_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
outer_cgi = {git = "https://github.com/SolraBizna/outer_cgi", rev = "dd59b3066e616a08e756f72de8dc3ab11b7036c4"}