[package]
name = "CVE-2020-15254_repair"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = {git = "https://github.com/crossbeam-rs/crossbeam", rev = "be327d581e8434a2ba41b74affc915f42d8abfcd"}