[package]
name = "CVE-2019-16144_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
generator = {git = "https://github.com/Xudong-Huang/generator-rs", rev = "156425ca9fdcce7d0dea4da8b46e4f4790e21914"}