[package]
name = "CVE-2021-45704_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
metrics-util = {git = "https://github.com/metrics-rs/metrics", rev = "5be6c93b6d186ca4745d1a7f2c1a42dee86c21e4"}